name: proyecto_grafos
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_speed_dial: ^5.0.0
  flutter_statusbarcolor_ns: ^0.5.0
  carousel_slider: ^4.0.0
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/

